services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./jobs:/opt/airflow/jobs
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workspace
    environment:
      PROJECT_DIR: ${PWD}
    command: airflow standalone

  pyspark:
    image: apache/spark:latest
    ports:
      - "4040:4040"
    volumes:
      - ./:/workspace
    working_dir: /workspace
    command: tail -f /dev/null